/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_Operandos (XDR *xdrs, Operandos *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Error (XDR *xdrs, Error *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 100))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ResultadoDivision (XDR *xdrs, ResultadoDivision *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->tipo))
		 return FALSE;
	switch (objp->tipo) {
	case 1:
		 if (!xdr_int (xdrs, &objp->ResultadoDivision_u.n))
			 return FALSE;
		break;
	case 2:
		 if (!xdr_float (xdrs, &objp->ResultadoDivision_u.x))
			 return FALSE;
		break;
	case 3:
		 if (!xdr_Error (xdrs, &objp->ResultadoDivision_u.error))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}
